### ISSUE TITLE
Google Play Store - Pre launch report problem

### ISSUE THREAD

**Issue by nickstamp93** [Ramotion/paper-onboarding-android#45]
Hello, i used your library for my new app. However, the pre-launch report on Play Store can't proceed beyond the intro slides, so it stucks on the first slide and never makes it to the actual app. I am guessing this is because the devices won't swipe to the next slide. Any solutions?

**Comment by golovin47** [comment]
Hi @nickstamp93. Please describe this issue in more details.

**Comment by nickstamp93** [comment]
Hello @golovin47 . Firstly, i don't think this is a library problem but i am just asking for a solution. When you upload the app in the play store there is a procedure called pre-launch report which runs the app on multiple devices. These devices are bots, not humans, and make random clicks and selections across the app to find problems, performance issues etc. 
Now the problem is that these bots can't recognize that they have to swipe to move to the next slide of the onboarding, so they are stuck on the first slide of the onboarding experience. Maybe this is an accessibility issue of this library?

**Comment by golovin47** [comment]
@nickstamp93  Because this lib implements it's own logic placed in simple RelativeLayout, pre-launch bots may just don't know how to deal with it, they don't know that this is a view which you should swipe. This may be the possible cause. To be sure if this is the case, remove this lib from your project and test without it, if pre-launch report will be ok, than this lib causes the pre-launch report stuck. If you tested app by yourself and everything works fine, you may ignore the pre-launch report and release anyway. Otherwise you may fork this lib and modify it the way you need.
